version: '3'
services:
    mongodb:
        container_name: mongodb
        restart: always
        image: mongo
        environment:
          - MONGO_INITDB_ROOT_USERNAME=docker
          - MONGO_INITDB_ROOT_PASSWORD=mongopw
        ports:
            - '27017:27017'
    web:
        build: .
        restart: always
        container_name: web
        ports:
            - '5000:5000'
    signal:
        container_name: signal
        restart: always
        image: pupugggg/ws:latest
        ports:
            - '1234:1234'
